afx-training-roster/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  # These codes determine the url.
  # get: the url that displays the form
  # post or put: the url that the form's "submit" button leads to.

  # audition_controller
  get "/audition", to: "audition#index"
  post "/audition", to: "audition#create"

  get "/teamswitch", to: "team_switch_form#index"
  post "/teamswitch", to: "team_switch_form#create_team_switch_request", as: "team_switch_form"

  get "/dancer/:email", to: "dancer#find_team",
                        constraints: { email: %r{[^\/]+} }
end

afx-training-roster/app/controllers/audition_controller.rb
class AuditionController < ApplicationController
  def index
    @dancer = Dancer.new
  end

  def create
    @dancer = Dancer.new(dancer_params)
    success = @dancer.save
    render "audition/index" unless success
  end

  def edit
    @dancer = Dancer.find(params[:id])
  end

  def update
    # require 'pry-nav'; binding.pry
    @dancer = Dancer.find(params[:id])
    success = @dancer.update(dancer_params)
    render "audition/edit" unless success
  end

  private

    def dancer_params
      params
        .require(:dancer)
        .permit(
          :name,
          :email,
          :phone,
          :gender,
          :year,
          :dance_experience,
          :exp_interest,
          :tech_interest,
          :camp_interest,
          :reach_workshop_interest,
          :reach_news_interest,
        )
    end
end

afx-training-roster/app/views/audition/_fields.haml
- if @dancer.errors.any?
  %div Please fix the following errors:
  - @dancer.errors.full_messages.each do |message|
    %li= message

%table
  %tr
    %td
      Full Name
    %td
      - if f
        = f.text_field(:name, required: true, pattern: Dancer::NAME_PATTERN)
      - else
        = @dancer.name

  %tr
    %td
      Email
    %td
      - if f
        = f.text_field(:email, required: true, pattern: Dancer::EMAIL_PATTERN)
        %small
          We strongly recommend entering your primary email. Note that berkeley.com and berkeley.edu are very different!
      - else
        = @dancer.email

  %tr
    %td
      Phone
    %td
      - if f
        = f.text_field(:phone, required: true, pattern: Dancer::PHONE_PATTERN)
        %small
          MUST be XXX-XXX-XXXX format
      - else
        = @dancer.phone

  %tr
    %td
      Gender
    %td
      - if f
        = f.select(:gender, options_for_select(Dancer::GENDER_VALUES.invert, @dancer.gender), {include_blank: ""}, {required: true})
        %small
          This information is used to ensure teams are balanced, diverse, and inclusive. The form is processed by an algorithm and your response will be kept confidential within the AFX Dance Executive Board.
      - else
        = Dancer::GENDER_VALUES[@dancer.gender]

  %tr
    %td
      Year
    %td
      - if f
        = f.select(:year, options_for_select(Dancer::YEAR_VALUES.invert, @dancer.year), {include_blank: ""}, {required: true})
      - else
        = Dancer::YEAR_VALUES[@dancer.year]

  %tr
    %td
      Prior Dance Experience
    %td
      - if f
        = f.select(:dance_experience, options_for_select(Dancer::DANCE_EXPERIENCE_VALUES.invert, @dancer.dance_experience), {include_blank: ""}, {required: true})
      - else
        = Dancer::DANCE_EXPERIENCE_VALUES[@dancer.dance_experience]

  - if Dancer::SHOW_CAMP_INTEREST
    %tr
      %td
        Interested in AFXsi Dance Camp?
      %td
        - if f
          = f.select(:camp_interest, options_for_select(Dancer::BOOLEAN_OPTION_VALUES.invert, @dancer.camp_interest), {include_blank: ""}, {required: true})
          %small
            Applications are due Tuesday, June 25th at 5PM. If you would like to apply, please check out our event page on Facebook from the Gen Audition page!
        - else
          = Dancer::BOOLEAN_OPTION_VALUES[@dancer.camp_interest]
  - else
    = f.hidden_field(:camp_interest, value: 'field_hidden') if f

  - if Dancer::SHOW_EXP_INTEREST
    %tr
      %td
        Are you interested in EXP?
      %td
        - if f
          = f.select(:exp_interest, options_for_select(Dancer::BOOLEAN_OPTION_VALUES.invert, @dancer.exp_interest), {include_blank: ""}, {required: true})
          %small
            EXP is a dance organization partnered with AFX that focuses on dancer growth through urban and hip-hop fundamentals and freestyle training! Please indicate if you are interested in receiving more information via email!
        - else
          = Dancer::BOOLEAN_OPTION_VALUES[@dancer.exp_interest]
  - else
    = f.hidden_field(:exp_interest, value: 'field_hidden') if f

  - if Dancer::SHOW_TECH_INTEREST
    %tr
      %td
        Are you interested in AFX Tech?
      %td
        - if f
          = f.select(:tech_interest, options_for_select(Dancer::BOOLEAN_OPTION_VALUES.invert, @dancer.tech_interest), {include_blank: ""}, {required: true})
          %small
            AFX Tech is a project-based technical organization that contributes to the Berkeley Dance Community through a variety of outlets, from front-end web development/design to back-end algorithmic programming.
        - else
          = Dancer::BOOLEAN_OPTION_VALUES[@dancer.tech_interest]
  - else
    = f.hidden_field(:tech_interest, value: 'field_hidden') if f

  - if Dancer::SHOW_REACH_INTEREST
    %tr
      %td
        Interested in AFX Reach?
        %br
        %small
          We expand AFX’s community involvement
          %br
          via workshops and dance exercises at
          %br
          schools, nursing care facilities, and youth
          %br
          programs, and host community service
          %br
          and charity events.
      %td
        - if f
          = f.select(:reach_workshop_interest, options_for_select(Dancer::BOOLEAN_OPTION_VALUES.invert, @dancer.reach_workshop_interest), {include_blank: ""}, {required: true})
          %small
            I’m interested in teaching choreography at AFX Reach workshops.
          = f.select(:reach_news_interest, options_for_select(Dancer::BOOLEAN_OPTION_VALUES.invert, @dancer.reach_news_interest), {include_blank: ""}, {required: true})
          %small
            I’m interested in the AFX Reach newsletter to be notified of our community involvements!
        - else
          = Dancer::BOOLEAN_OPTION_VALUES[@dancer.reach_workshop_interest]
          = Dancer::BOOLEAN_OPTION_VALUES[@dancer.reach_news_interest]
  - else
    = f.hidden_field(:reach_workshop_interest, value: 'field_hidden') if f
    = f.hidden_field(:reach_news_interest, value: 'field_hidden') if f


  - if f
    %tr
      %td
      %td
        = f.submit "I'm ready to audition!"

afx-training-roster/app/views/audition/_form_fields.haml
- if @dancer.errors.any?
  - @dancer.errors.full_messages.each do |message|
    %li= message
%table
  %tr
    %td
      Name
    %td
      = f.text_field :name, required: true, placeholder: "Name"
  %tr
  %tr
    %td
      Phone number
    %td
      = f.text_field :email, required: true, placeholder: "Email",                    |
        pattern: "[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*" |
  %tr
= f.text_field :name, required: true, placeholder: "Name"
%br/
/ Email regex copied from http://emailregex.com/
= f.text_field :email, required: true, placeholder: "Email",                    |
  pattern: "[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*" |
%br/
= f.text_field :phone, required: true, placeholder: "Phone Number (###-###-####)", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}", |
  id: "phone"                                                                                                             |
%small     Must follow this format: ###-###-####
%br/
%br/
"This information is used to ensure teams are balanced, diverse, and inclusive. The form is processed by an algorithm and your response will not be seen beyond executive board."
= f.select :gender, options_for_select([                   |
    ['Male', 'male'],                                      |
    ['Female', 'female'],                                  |
    ['Transgender male', 'trans-male'],                    |
    ['Transgender female', 'trans-female'],                |
    ['Genderqueer/gender nonconforming', 'nonconforming'], |
    ['Decline to answer', 'decline'],                      |
    ['Other', 'other'],                                    |
  ], @dancer.gender), {prompt: "Gender"}, required: true   |
%br/
= f.select :year, options_for_select([               |
    ['Freshman or younger', '1'],                    |
    ['Sophomore', '2'],                              |
    ['Junior', '3'],                                 |
    ['Senior or older', '4']                         |
  ], @dancer.year), {prompt: 'Year'}, required: true |
%br/
= f.select :dance_experience, options_for_select([                    |
    ['No', 'No'],                                                     |
    ['Yes, and I have been in AFX before', 'YesYesAFX'],              |
    ['Yes, but I have not been in AFX before', 'YesNoAFX'],           |
  ]), {prompt: "Do you have prior dance experience?"}, required: true |
%br/
= f.select :exp_interest, options_for_select([    |
    ['Yes', true],                                |
    ['No', false],                                |
  ]), {prompt: "Interest in EXP"}, required: true |
%br/
= f.select :tech_interest, options_for_select([        |
    ['Yes', true],                                     |
    ['No', false],                                     |
  ]), {prompt: "Interest in AFX Tech"}, required: true |
%br/
= f.select :reach_workshop_interest, options_for_select([        |
    ['Yes', true],                                     |
    ['No', false],                                     |
  ]), {prompt: "Interest in Teaching AFX Reach Workshops"}, required: true |
%br/
= f.select :reach_news_interest, options_for_select([        |
    ['Yes', true],                                     |
    ['No', false],                                     |
  ]), {prompt: "Interest in AFX Reach Newsletter"}, required: true |
%br/
%br/
= f.submit "I'm ready to audition!"
%br/
%br/
%small
  This form was created and is managed by the AFX Tech Committee. :)

afx-training-roster/app/views/audition/create.html.haml
%body#audition-form-body
  .audition-form
    .audnum
      %h3
        %div
          %b>= @dancer.name
        %div
          your audition number is
          %b= @dancer.id

  %br/
  %center= link_to "BACK TO FORM", audition_path, style: "color: white; font-size: 18px;"

afx-training-roster/app/views/audition/edit.html.haml
%body#audition-form-body
  = form_for( |
      :dancer, method: "put", |
      url: {action: "update", id: @dancer.id}, |
      html: {autocomplete: "off", class: "audition-form"}, |
    ) do |f| |
    = render partial: "audition/fields", locals: {f: f}

afx-training-roster/app/views/audition/index.html.haml
%body#audition-form-body
  = form_for( |
      :dancer, |
      url: audition_path, |
      html: {autocomplete: "off", class: "audition-form"}, |
    ) do |f| |
    %h2 AFX AUDITIONS
    = render partial: "audition/fields", locals: {f: f}

afx-training-roster/app/views/audition/update.html.haml
%body#audition-form-body
  .audition-form
    .audnum
      %h3
        %div
          %b>= @dancer.name
          , you have successfully updated your info.
        %br
        %div
          Your audition number is still
          %b= @dancer.id
          \.

  %br/
  %center= link_to "BACK TO FORM", audition_path, style: "color: white; font-size: 18px;"