afx-training-roster/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  # These codes determine the url.
  # get: the url that displays the form
  # post or put: the url that the form's "submit" button leads to.

  # audition_controller
  get "/audition", to: "audition#index"
  post "/audition", to: "audition#create"

  get "/teamswitch", to: "team_switch_form#index"
  post "/teamswitch", to: "team_switch_form#create_team_switch_request", as: "team_switch_form"

  get "/dancer/:email", to: "dancer#find_team",
                        constraints: { email: %r{[^\/]+} }
end

afx-training-roster/app/views/admin/_demographics.html.erb
<div>
  <% if team_id == nil %>
    <div style="display:flex">
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.group(:gender).count, title: "Gender", width: "300px", margin: "auto"%>
        </div>
      </div>
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.group(:year).count, title: "Year", width: "300px", margin: "auto"%>
        </div>
      </div>
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.group(:dance_experience).count, title: "Experience", width: "300px", margin: "auto"%>
        </div>
      </div>
    </div>
  <% else %>
    <div style="display:flex">
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.joins(:dancers_teams).where(dancers_teams: {team_id: team_id}).group(:gender).count, title: "Gender", width: "300px"%>
        </div>
      </div>
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.joins(:dancers_teams).where(dancers_teams: {team_id: team_id}).group(:year).count, title: "Year", width: "300px"%>
        </div>
      </div>
      <div style="flex-grow:1; height:300px">
        <div style="width:300px; margin:auto">
          <%= pie_chart Dancer.joins(:dancers_teams).where(dancers_teams: {team_id: team_id}).group(:dance_experience).count, title: "Experience", width: "300px"%>
        </div>
      </div>
    </div>
    
  <% end %>
</div>

afx-training-roster/app/views/admin/_edit_teamswitch.html.erb
<style>
#audition-form-body
{
  background: url('/assets/blurred-bg.jpg') no-repeat center center fixed;
  vertical-align: middle;
  text-align: left;
}
.audition-form
{
  font-family: 'Open Sans Condensed', arial, sans;
  width: 600px;
  padding: 30px;
  background: #fff;
  opacity: 0.7;
  margin: 0 auto;
  box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.22);
  -moz-box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.22);
  -webkit-box-shadow:  0px 0px 30px rgba(0, 0, 0, 0.22);
}
.audition-form h2
{
  background: #4D4D4D;
  text-transform: uppercase;
  font-family: 'Open Sans Condensed', sans-serif;
  color: #FFF;
  font-size: 34px;
  text-align: center;
  font-weight: bold;
  padding: 20px;
  margin: -30px -30px 30px -30px;
}
.audition-form td:first-child
{
  vertical-align: middle;
  font-size: 1.2em;
  text-align: right;
  white-space: nowrap;
}
.audition-form input[type="text"],
.audition-form input[type="date"],
.audition-form input[type="datetime"],
.audition-form input[type="email"],
.audition-form input[type="number"],
.audition-form input[type="search"],
.audition-form input[type="time"],
.audition-form input[type="url"],
.audition-form input[type="password"],
.audition-form textarea,
.audition-form select
{
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  outline: none;
  display: block;
  width: 100%;
  padding: 7px;
  border: none;
  border-bottom: 1px solid #ddd;
  background: transparent;
  margin-bottom: 10px;
  font: 16px Arial, Helvetica, sans-serif;
  height: 45px;
}
.audition-form textarea
{
  height: 300px;
  resize:none;
  overflow-y: scroll;
}
.audition-form input[type="button"],
.audition-form input[type="submit"]
{
  -moz-box-shadow: inset 0px 1px 0px 0px #45D6D6;
  background-color: #000000 !important;
  opacity: 0.8;
  border: 1px solid #808080;
  border-radius: 0px;
  display: inline-block;
  cursor: pointer;
  color: #FFFFFF;
  font-family: 'Open Sans Condensed', sans-serif;
  font-size: 14px;
  padding: 8px 18px;
  text-decoration: none;
  text-transform: uppercase;
}
.audition-form input[type="button"]:hover,
.audition-form input[type="submit"]:hover
{
  background:linear-gradient(to bottom, #34CACA 5%, #30C9C9 100%);
  background-color:#34CACA;
}
.audnum h3
{
  background: #4D4D4D;
  width: 500px;
  opacity: 0.7;
  font-family: 'Open Sans Condensed', sans-serif;
  color: #fff;
  font-size: 32px;
  padding: 30px;
  margin: 50px auto;
  box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.22);
  -moz-box-shadow: 0px 0px 30px rgba(0, 0, 0, 0.22);
  -webkit-box-shadow:  0px 0px 30px rgba(0, 0, 0, 0.22);
}
.audition-form label
{
  -webkit-user-select: none;
}
/*.audition-form .availability-checkbox
{
  display: none;
}*/
.availability-display-free
{
  color: green;
}
.audition-form .availability-checkbox + .availability-display .availability-display-free
{
  display: none;
}
.audition-form .availability-checkbox:checked + .availability-display .availability-display-free
{
  display: inline;
}
.audition-form .availability-checkbox:checked + .availability-display .availability-display-busy
{
  display: none;
}
.times
{
  font-size: 16px;
  text-align: left
}
form p
{
margin: 1em 0;
}
.submit
{
  text-align: center;
}
html, body
{
  overflow: auto;
}
div.editable:hover {
  background-color: #f0f0f0;
}
</style>

<% @formfields = FormField.find_team_switch_fields %>
<% @updatedAt = FormField.last_updated_team_switch %>
<% @backupAt = FormField.last_backup_team_switch %>

<body id="audition-form-body">

<%= form_for :team_switch_request, :url => team_switch_form_path, :html => {:class => "audition-form"} do |f| %>

  <div class="editable" contenteditable="true", id="fd1">
    <%= @formfields[0] %>
  </div>

  <div class="times">

  <% if false %>

  # <p>Welcome to AFXsi 2018, AFX's 2018 Summer Intensive Program!

  # <p>Thank you for dancing with AFXsi 2018! Our team switch/drop form has now closed. If you have any personal concerns, please discuss with your current team's directors. Otherwise, please email any further questions to afxdanceviceexecutive@gmail.com. We hope you have a great summer!</p>

  <% else %>

  <div class="editable" contenteditable="true", id="fd2">
    <%= @formfields[1] %>
  </div>

  <div class="editable" contenteditable="true", id="fd3">
    <%= @formfields[2] %>
  </div>

  <div class="editable" contenteditable="true", id="fd4">
    <%= @formfields[3] %>
  </div>

  <%= f.text_field :name, required: true, placeholder: "FIRST AND LAST NAME", readonly: true %><br>
  <%= f.text_field :email, required: true, placeholder: "EMAIL", readonly: true %><br>
  <%= f.text_field :phone, required: true, placeholder: "PHONE: XXX-XXX-XXXX", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}", readonly: true %>

  <br><br>
  <b><hr></b>
  <br>

  <div class="editable" contenteditable="true", id="fd5">
    <%= @formfields[4] %>
  </div>

  <div class="editable" contenteditable="true", id="fd6">
    <%= @formfields[5] %>
  </div>

  <%= f.collection_check_boxes(
        :available_team_ids,
        Team.project_teams.sort_by(&:practice_time_sort_string),
        :id,
        :name
      ) do |option| %>
    <% next if option.object.practice_time.blank? || option.object.practice_time[0] == " " %>
    <div><label>
      <%= option.check_box(class: "availability-checkbox availability-checkbox-project") %>
      <span class="availability-display" style="display: none">
        <code class="availability-display-busy">BUSY</code>
        <code class="availability-display-free">FREE</code>
      </span>
      <%= option.object.practice_time %>
    </label></div>
  <% end %>

  <div class="editable" contenteditable="true", id="fd7">
    <%= @formfields[6] %>
  </div>

  <br><br>
  <hr><br>

  <div class="editable" contenteditable="true", id="fd8">
   <%= @formfields[7] %>
  </div>

  <div class="editable" contenteditable="true", id="fd9">
    <%= @formfields[8] %>
  </div>

  <%= f.collection_check_boxes(
        :available_team_ids,
        Team.training_teams.sort_by(&:practice_time_sort_string),
        :id,
        :name
      ) do |option| %>
    <% next if option.object.practice_time.blank? || option.object.practice_time[0] == " " %>
    <div><label>
      <%= option.check_box(class: "availability-checkbox availability-checkbox-training") %>
      <span class="availability-display" style="display: none">
        <code class="availability-display-busy">BUSY</code>
        <code class="availability-display-free">FREE</code>
      </span>
      <%= option.object.practice_time %>
    </label></div>
  <% end %>

  <div class="editable" contenteditable="true", id="fd10">
    <%= @formfields[9] %>
  </div>

  <hr><br>

  <div class="editable" contenteditable="true", id="fd11">
    <%= @formfields[10] %>
  </div>

  <div class="editable" contenteditable="true", id="fd12">
    <%= @formfields[11] %>
  </div>

  <%= f.collection_check_boxes(
        :available_team_ids,
        Team.drop_teams.sort_by(&:practice_time_sort_string),
        :id,
        :name
      ) do |option| %>
    <div><label>
      <%= option.check_box(class: "availability-checkbox availability-checkbox-drop") %> Yes, I would like to withdraw from AFX Fall 2019 Project/Training. I acknowledge that my decision is final and that once I submit the form, I will no longer be able to join any team practice or perform in any AFX set this semester (NO EXCEPTIONS). If I violate these conditions and do not pay AFX dues, I will be charged at any time.
    </label></div>
  <% end %>

  <div class="editable" contenteditable="true", id="fd13">
    <%= @formfields[12] %>
  </div>

  <hr><br>

  <div class="editable" contenteditable="true", id="fd14">
    <%= @formfields[13] %>
  </div>

  <%= f.text_area :reason, required: true, placeholder: "Reason", readonly: true %>

  <br><br><hr><br>

  <div class="editable" contenteditable="true", id="fd15">
    <%= @formfields[14] %>
  </div>

  <p>
    <%= f.check_box(:double_check, {})%>
    <label>Yes</label>
  </p>

  <div class="editable" contenteditable="true", id="fd16">
    <%= @formfields[15] %>
  </div>


  <div>          <!-- THIS <i> or <div> IS IMPORTANT FOR SOME REASON DO NOT REMOVE (we have no idea why someone help pls) -->

  <p> Last edited: <%= @updatedAt %> </p>
  <p> Last backup: <%= @backupAt %> </p>

  </div>
  <% end %>

<% end %>

<%= form_with(url: { action: "update" }) do %>

  <input id="fdfd1" name="1" type="hidden" />
  <input id="fdfd2" name="2" type="hidden" />
  <input id="fdfd3" name="3" type="hidden" />
  <input id="fdfd4" name="4" type="hidden" />
  <input id="fdfd5" name="5" type="hidden" />
  <input id="fdfd6" name="6" type="hidden" />
  <input id="fdfd7" name="7" type="hidden" />
  <input id="fdfd8" name="8" type="hidden" />
  <input id="fdfd9" name="9" type="hidden" />
  <input id="fdfd10" name="10" type="hidden" />
  <input id="fdfd11" name="11" type="hidden" />
  <input id="fdfd12" name="12" type="hidden" />
  <input id="fdfd13" name="13" type="hidden" />
  <input id="fdfd14" name="14" type="hidden" />
  <input id="fdfd15" name="15" type="hidden" />
  <input id="fdfd16" name="16" type="hidden" />

  <input style="margin-bottom: 8px" type="submit" name="commit" value="Save Changes" data-disable-with="Save Changes" id="submit_button_thing">

<% end %>

<script>

  function fill_fields() {
    for (i = 1; i < 17; i++) {
      var first = document.getElementById('fd' + i), second = document.getElementById('fdfd' + i);
      second.value = first.innerHTML;
    }
  }

  document.getElementById("submit_button_thing").addEventListener("click", fill_fields);

</script>

<%= form_with(url: { action: "set" }) do %>

  <input id="ab1" name="1" type="hidden" />
  <input id="ab2" name="2" type="hidden" />
  <input id="ab3" name="3" type="hidden" />
  <input id="ab4" name="4" type="hidden" />
  <input id="ab5" name="5" type="hidden" />
  <input id="ab6" name="6" type="hidden" />
  <input id="ab7" name="7" type="hidden" />
  <input id="ab8" name="8" type="hidden" />
  <input id="ab9" name="9" type="hidden" />
  <input id="ab10" name="10" type="hidden" />
  <input id="ab11" name="11" type="hidden" />
  <input id="ab12" name="12" type="hidden" />
  <input id="ab13" name="13" type="hidden" />
  <input id="ab14" name="14" type="hidden" />
  <input id="ab15" name="15" type="hidden" />
  <input id="ab16" name="16" type="hidden" />

  <input style="margin-bottom: 8px" type="submit" name="commit" value="Save Changes and Set as Backup" data-disable-with="Save Changes and Set as Backup" id="set_and_save">

<% end%>

<script>
    function fill_and_set() {
      for (i = 1; i < 17; i++) {
        var first = document.getElementById('fd' + i), second = document.getElementById('ab' + i);
        second.value = first.innerHTML;
      }
    }

  document.getElementById("set_and_save").addEventListener("click", fill_and_set);
</script>

<%= form_with(url: { action: "revert" }) do %>

  <input type="submit" name="commit" value="Revert to Backup" data-disable-with="Revert to Backup" id="set_and_save">

<% end%>
</body>

afx-training-roster/app/views/admin/_team_preferences.html.erb
<style>
.content-container {
  width: 50%;
}

table, td, th {
  border: 1px solid black;
  border-collapse: collapse;
}

form input {
  margin: 4px 0px;
}
</style>

<%
  @teams = Team.project_teams
  preferences = TeamPreference.all
  @team_submitted_preferences = Hash.new

  for t in @teams
    @team_submitted_preferences[t.id] = false
  end

  for pref in preferences
    @team_submitted_preferences[pref.team_id] = true
  end
%>

<div class="content-container">
  <table>
    <tr>
      <td>
        Team
      </td>
      <td>
        Preferences Submitted
      </td>
    </tr>
    <% for team in @teams %>
    <tr>
      <td>
        <%= team.name %>
      </td>
      <td>
        <%= @team_submitted_preferences[team.id] %>
      </td>
    </tr>
    <% end %>
  </table>

  <% if disable_button %>
    <h3 style="color: #BD2100">Create Teams button is disabled because team rosters have changed since initial creation</h3>
  <% end %>

  <%= form_tag action: "create_project_teams", method: :post do %>
    <p>Max Team Size<p>
    <%= number_field_tag "team_size", nil, min: 1, step: 1, required: true %>
    <%= submit_tag 'Create Project Teams', disabled: disable_button %>
  <% end %>

  <p><%= params[:errors] %></p>

  <% if params[:teams] %>
    <h2>Results:</h2>
    <%
      result_teams = params[:teams]
      lengths = []
      puts result_teams
      for value in result_teams.values
        lengths.push(value.length())
      end
      maxLength = lengths.max()
    %>
    <table>
      <tr>
        <% for key in result_teams.keys %>
          <td>
            <%= Team.find(key).name %>
          </td>
        <% end %>
      </tr>
      <% for index in 0..maxLength-1 %>
        <tr>
        <% for val in result_teams.values %>
          <% if index < val.length() %>
            <td>
              <%= val[index] %>
            </td>
          <% else %>
            <td>
            </td>
          <% end %>
        <% end %>
        </tr>
      <% end %>
    </table>
    <h2>Dancers in Limbo:</h2>
    <%
      limbo = params[:limbo]
    %>
    <% if limbo %>
    <table>
      <% for index in 0..limbo.length()-1 %>
        <tr>
            <td>
              <%= limbo[index] %>
            </td>
        </tr>
      <% end %>
    </table>
    <% else %>
    <p>(None)<p>
    <% end %>
  <% end %>

  <h3>Button below clears existing created teams (Use with caution)</h3>
  <%= button_to 'CLEAR TEAMS', { action: "delete_teams" }, method: :post, data: { confirm: "You are about to delete all teams in the database. Are you sure you want to do this?" } %>
  <p><%= params[:delete_teams_message] %></p>
</div>